import { NextRequest } from "next/server";
import { connectDB } from "@/lib/mongodb";
import { ImageAsset, DocumentAsset } from "@/lib/models";
import { requireRole, json, badRequest, serverError } from "@/lib/api-helpers";
import { uploadToR2, isR2Configured } from "@/lib/r2";

// A batch is a handful of files; uploads are I/O-bound against R2.
export const maxDuration = 120;

const R2_UPLOAD_CONCURRENCY = 8;
const MAX_ASSET_BYTES = 50 * 1024 * 1024;

/**
 * Storage keys come out of a user-supplied ZIP, so they are untrusted input
 * even though only an admin can reach this route. Anything that isn't a plain
 * `images/…` or `documents/…` path is rejected outright — without this, a
 * crafted archive could place objects anywhere in the bucket.
 */
function isSafeStorageKey(key: unknown): key is string {
  if (typeof key !== "string" || key.length === 0 || key.length > 512) {
    return false;
  }
  if (!key.startsWith("images/") && !key.startsWith("documents/")) return false;
  if (key.includes("..") || key.includes("\\") || key.includes("//")) {
    return false;
  }
  if (key.endsWith("/")) return false;
  // Reserved manifest names are regenerated by the backup route, never uploaded.
  if (key.endsWith("/_metadata.json")) return false;
  return true;
}

/** SVG is never accepted on the normal upload path; don't let restore be a hole. */
function isRejectedType(key: string, mime: string): boolean {
  return mime === "image/svg+xml" || /\.svgz?$/i.test(key);
}

type MetaMap = Record<string, Record<string, unknown> | undefined>;

const MIME_BY_EXT: Record<string, string> = {
  webp: "image/webp",
  jpg: "image/jpeg",
  jpeg: "image/jpeg",
  png: "image/png",
  gif: "image/gif",
  avif: "image/avif",
  pdf: "application/pdf",
  doc: "application/msword",
  docx: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  xls: "application/vnd.ms-excel",
  xlsx: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  txt: "text/plain",
  csv: "text/csv",
};

/**
 * Content-Type has to come from the key's extension when the archive carries no
 * metadata for it. Defaulting by prefix alone would stamp `image/webp` onto
 * every untracked `.jpeg`/`.png`, and R2 serves that header straight to
 * browsers. A ZIP entry's blob type is empty, so it can't be relied on either.
 */
function mimeForKey(key: string, metaMime: unknown, blobType: string): string {
  if (typeof metaMime === "string" && metaMime.length > 0) return metaMime;
  const ext = key.split(".").pop()?.toLowerCase() ?? "";
  if (MIME_BY_EXT[ext]) return MIME_BY_EXT[ext];
  if (blobType) return blobType;
  return key.startsWith("images/") ? "image/webp" : "application/octet-stream";
}

function str(v: unknown, fallback = ""): string {
  return typeof v === "string" && v.length > 0 ? v : fallback;
}

function num(v: unknown, fallback = 0): number {
  return typeof v === "number" && Number.isFinite(v) ? v : fallback;
}

// Mirrors the ImageAsset schema enum — an out-of-range value from a
// hand-edited archive would otherwise fail Mongoose validation mid-batch.
const IMAGE_CATEGORIES = [
  "department",
  "faculty",
  "hero",
  "campus",
  "program",
  "recruiter",
  "testimonial",
  "other",
];

function category(v: unknown): string {
  return typeof v === "string" && IMAGE_CATEGORIES.includes(v) ? v : "other";
}

async function mapWithConcurrency<T, R>(
  items: T[],
  limit: number,
  fn: (item: T) => Promise<R>,
): Promise<R[]> {
  const results = new Array<R>(items.length);
  let cursor = 0;
  const workers = Array.from(
    { length: Math.min(limit, items.length) },
    async () => {
      for (let i = cursor++; i < items.length; i = cursor++) {
        results[i] = await fn(items[i]!);
      }
    },
  );
  await Promise.all(workers);
  return results;
}

/**
 * Second half of a restore: push the ZIP's binaries back into R2 and re-create
 * their tracking rows. The client sends these in small batches because a full
 * archive is tens of megabytes and would hit reverse-proxy body limits as a
 * single request.
 */
export async function POST(req: NextRequest) {
  const { session, error } = await requireRole(req, "admin");
  if (error) return error;

  if (!isR2Configured()) {
    return badRequest(
      "R2 storage is not configured — cannot restore images or documents",
    );
  }

  let form: FormData;
  try {
    form = await req.formData();
  } catch {
    return badRequest("Expected a multipart/form-data body");
  }

  let imageMeta: MetaMap = {};
  let docMeta: MetaMap = {};
  try {
    const im = form.get("imageMeta");
    if (typeof im === "string") imageMeta = JSON.parse(im) as MetaMap;
    const dm = form.get("docMeta");
    if (typeof dm === "string") docMeta = JSON.parse(dm) as MetaMap;
  } catch {
    return badRequest("Invalid metadata JSON");
  }

  const entries = form
    .getAll("files")
    .filter((f): f is File => f instanceof File);
  if (entries.length === 0) return badRequest("No files in batch");

  // The browser cannot put a path in a FormData filename reliably, so keys
  // travel alongside the files in matching order.
  const rawKeys = form.getAll("keys").map(String);
  if (rawKeys.length !== entries.length) {
    return badRequest("keys/files length mismatch");
  }

  try {
    await connectDB();

    const uploaded: string[] = [];
    const failed: string[] = [];

    const results = await mapWithConcurrency(
      entries.map((file, i) => ({ file, key: rawKeys[i]! })),
      R2_UPLOAD_CONCURRENCY,
      async ({ file, key }) => {
        if (!isSafeStorageKey(key)) {
          return { key, ok: false, reason: "unsafe storage key" };
        }
        if (file.size > MAX_ASSET_BYTES) {
          return { key, ok: false, reason: "exceeds 50MB" };
        }
        const isImage = key.startsWith("images/");
        const meta = (isImage ? imageMeta : docMeta)[key];
        const mime = mimeForKey(key, meta?.mime_type, file.type);
        if (isRejectedType(key, mime)) {
          return { key, ok: false, reason: "SVG is not permitted" };
        }

        try {
          const buffer = Buffer.from(await file.arrayBuffer());
          const url = await uploadToR2(key, buffer, mime);

          // No metadata means the archive held a file that never had a tracking
          // row (seeded assets under images/programs/…, images/hod/…). Put the
          // bytes back but don't invent a media-library entry that the original
          // install didn't have.
          if (!meta) return { key, ok: true, reason: "" };

          if (isImage) {
            await ImageAsset.findOneAndUpdate(
              { storage_key: key },
              {
                $set: {
                  filename: str(meta.filename, key.split("/").pop() ?? key),
                  storage_key: key,
                  url,
                  alt_text: str(meta.alt_text),
                  category: category(meta.category),
                  institution: str(meta.institution, "all"),
                  file_size: num(meta.file_size, buffer.length),
                  mime_type: mime,
                  ...(typeof meta.width === "number"
                    ? { width: meta.width }
                    : {}),
                  ...(typeof meta.height === "number"
                    ? { height: meta.height }
                    : {}),
                  ...(typeof meta.ratio_type === "string"
                    ? { ratio_type: meta.ratio_type }
                    : {}),
                  ...(typeof meta.aspect_ratio === "string"
                    ? { aspect_ratio: meta.aspect_ratio }
                    : {}),
                  uploaded_by: str(
                    meta.uploaded_by,
                    session!.user?.email ?? "",
                  ),
                },
              },
              { upsert: true },
            );
          } else {
            await DocumentAsset.findOneAndUpdate(
              { storage_key: key },
              {
                $set: {
                  filename: str(meta.filename, key.split("/").pop() ?? key),
                  storage_key: key,
                  url,
                  mime_type: mime,
                  file_size: num(meta.file_size, buffer.length),
                  uploaded_by: str(
                    meta.uploaded_by,
                    session!.user?.email ?? "",
                  ),
                },
              },
              { upsert: true },
            );
          }
          return { key, ok: true, reason: "" };
        } catch (err) {
          console.error(`[restore-assets] ${key}:`, err);
          return { key, ok: false, reason: String(err) };
        }
      },
    );

    for (const r of results) {
      if (r.ok) uploaded.push(r.key);
      else failed.push(`${r.key}: ${r.reason}`);
    }

    return json({
      uploaded: uploaded.length,
      failed: failed.length,
      errors: failed.length > 0 ? failed : undefined,
    });
  } catch (e) {
    console.error("[site-config/restore-assets]", e);
    return serverError();
  }
}
