import type { MetadataRoute } from "next";

const BASE_URL = "https://jct.ac.in";

export default function sitemap(): MetadataRoute.Sitemap {
  const staticRoutes = [
    "/",
    "/about",
    "/about/institution",
    "/about/vision-mission",
    "/about/chairmans-message",
    "/about/principals-message",
    "/about/history",
    "/about/leadership",
    "/about/organizational-structure",
    "/about/governing-council",
    "/about/strategic-plan",
    "/admissions",
    "/admissions/why-jct",
    "/admissions/programs",
    "/admissions/eligibility",
    "/admissions/prospectus",
    "/admissions/seats",
    "/admissions/scholarships",
    "/admissions/fee-structure",
    "/admissions/process",
    "/admissions/apply",
    "/academics",
    "/academics/programs",
    "/academics/departments",
    "/academics/calendar",
    "/academics/regulations",
    "/academics/curriculum",
    "/academics/council",
    "/engineering",
    "/arts-science",
    "/polytechnic",
    "/placements",
    "/placements/statistics",
    "/placements/recruiters",
    "/placements/internships",
    "/placements/career-development",
    "/placements/industry-mous",
    "/placements/alumni-stories",
    "/research",
    "/research/policy",
    "/research/rnd-cell",
    "/research/centres",
    "/research/publications",
    "/research/funded-projects",
    "/research/patents",
    "/research/innovation",
    "/research/workshops",
    "/campus-life",
    "/campus-life/facilities",
    "/campus-life/hostel",
    "/campus-life/library",
    "/campus-life/laboratories",
    "/campus-life/sports",
    "/campus-life/clubs",
    "/campus-life/activities",
    "/campus-life/gallery",
    "/campus-life/news-events",
    "/examinations",
    "/examinations/cell",
    "/examinations/passing-board",
    "/examinations/results",
    "/examinations/notifications",
    "/governance",
    "/governance/anti-ragging",
    "/governance/sc-st-cell",
    "/governance/icc",
    "/governance/grievance",
    "/governance/women-empowerment",
    "/governance/student-welfare",
    "/governance/equal-opportunity",
    "/quality",
    "/quality/accreditations",
    "/quality/iqac",
    "/quality/feedback",
    "/quality/awards",
    "/mandatory-disclosure",
    "/mandatory-disclosure/code-of-conduct",
    "/mandatory-disclosure/policies",
    "/mandatory-disclosure/ethics",
    "/mandatory-disclosure/hr-manual",
    "/mandatory-disclosure/survey",
    "/mandatory-disclosure/privacy",
    "/mandatory-disclosure/terms",
    "/mandatory-disclosure/disclaimer",
    "/contact",
  ];

  return staticRoutes.map((route) => ({
    url: `${BASE_URL}${route}`,
    lastModified: new Date(),
    changeFrequency: route === "/" ? "weekly" : "monthly",
    priority: route === "/" ? 1 : route.split("/").length <= 2 ? 0.8 : 0.6,
  }));
}
